# Generated by Django 4.2.10 on 2024-04-09 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('take_date', models.DateTimeField(null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Open'), (2, 'Completed'), (3, 'Expired')], default=1)),
                ('duration', models.IntegerField(help_text='Save in minutes')),
                ('score', models.IntegerField(null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizes', to='courses.courses')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('deadline', models.DateTimeField()),
                ('sent_date', models.DateTimeField()),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Open'), (2, 'Completed'), (3, 'Expired')], default=1)),
                ('student_comment', models.TextField(blank=True, null=True)),
                ('instructor_comment', models.TextField(blank=True, null=True)),
                ('score', models.IntegerField(null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.courses')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_comments', to='people.people')),
                ('last_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_sender_assignments', to='people.people')),
            ],
        ),
    ]
