# Generated by Django 4.2.10 on 2024-07-25 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapingActionList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('last_used_datetime', models.DateTimeField()),
                ('cooldown_on_minute', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ScrapingBrowser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ScrapingQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_datetime', models.DateTimeField(auto_created=True)),
                ('comment', models.TextField()),
                ('parameter', models.JSONField()),
                ('response', models.JSONField(default=None, null=True)),
                ('start_datetime', models.DateTimeField(default=None, null=True)),
                ('end_datetime', models.DateTimeField(default=None, null=True)),
            ],
        ),
    ]
