# Generated by Django 4.2.10 on 2024-07-25 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapingbrowser',
            name='last_login',
            field=models.DateTimeField(null=True),
        ),
    ]
