# Generated by Django 4.2.10 on 2024-04-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('type', models.IntegerField(choices=[(1, 'Student'), (2, 'Lecture')])),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=14)),
            ],
        ),
    ]
