# Generated by Django 4.2.10 on 2024-06-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BinusAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authentication1', models.TextField()),
                ('authentication2', models.TextField()),
            ],
        ),
    ]
