# Generated by Django 4.2.10 on 2024-04-07 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('period', '0003_alter_period_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(db_column='subject_code', max_length=300)),
                ('name', models.CharField(max_length=300)),
                ('code', models.CharField(max_length=300)),
                ('type', models.IntegerField(choices=[(1, 'CL'), (2, 'LEC')])),
                ('url', models.CharField(max_length=500)),
                ('period', models.ForeignKey(db_column='period_id', on_delete=django.db.models.deletion.CASCADE, to='period.period')),
            ],
        ),
    ]
